name: Lint Groq API Library

on:
  push:
    branches-ignore: ["master"]
    paths:
      - "./**"
      - ".github/workflows/lint.yaml"
  pull_request:
    paths:
      - "./**"
      - ".github/workflows/lint.yaml"

jobs:
  lint:
    name: Lint Groq API Library
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-restore --no-build --verbosity normal
